# Generated by Django 4.2.6 on 2023-11-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0002_rename_descreption_queue_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
