# Generated by Django 4.2.6 on 2023-10-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='comment',
            field=models.TextField(),
        ),
    ]
