# Generated by Django 4.2.7 on 2023-11-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
