# Generated by Django 4.2.6 on 2023-11-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_alter_submission_address_alter_submission_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
