# Generated by Django 4.2.7 on 2024-04-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_closers_leaderstatus_submission_closer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='insurance_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
