# Generated by Django 4.2.7 on 2023-11-20 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionproducts',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_products', to='submissions.submission'),
        ),
        migrations.AddField(
            model_name='product',
            name='submissions',
            field=models.ManyToManyField(through='products.SubmissionProducts', to='submissions.submission'),
        ),
    ]
