# Generated by Django 4.2.6 on 2023-10-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionproducts',
            name='count',
            field=models.SmallIntegerField(default=0),
        ),
    ]
